const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.advert,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Particles,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.gamepad,
		C3.Plugins.TiledBg,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Function,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Date,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Persist,
		C3.Plugins.List,
		C3.Plugins.NinePatch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.advert.Cnds.OnRewardedCancelled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Cnds.OnInterstitialComplete,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.TextBox.Acts.ScrollToBottom,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.advert.Cnds.OnInterstitialFailedToLoad,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Text.Cnds.OnDestroyed,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.advert.Acts.CreateRewardedInterstitial,
		C3.Plugins.advert.Cnds.OnRewardedInterstitialComplete,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Cnds.OnProgress,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.Arr.Acts.Reverse,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Exps.fps
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{AlmacenamientoLocal: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{AnuncioEnMóvil: 0},
	{AJAX: 0},
	{JSON: 0},
	{ENVIAR: 0},
	{RECIVIR: 0},
	{esta_andando: 0},
	{slot1: 0},
	{slot2: 0},
	{slot3: 0},
	{icono: 0},
	{AdvancedRandom: 0},
	{AirDust: 0},
	{AvailablePositions: 0},
	{GameData: 0},
	{Tween: 0},
	{Timer: 0},
	{GameManager: 0},
	{Gamepad: 0},
	{Level: 0},
	{Sparks: 0},
	{TiledBackground: 0},
	{Background: 0},
	{Blade: 0},
	{BladeSmoother: 0},
	{DrawingCanvas: 0},
	{Fade: 0},
	{FireParticles: 0},
	{GameManager2: 0},
	{VectorX: 0},
	{VectorY: 0},
	{RotationSpeed: 0},
	{Luminosity: 0},
	{HalfObject: 0},
	{InstructionsText: 0},
	{JuiceParticles: 0},
	{Object: 0},
	{Flash: 0},
	{ScoreText: 0},
	{SliceText: 0},
	{SmokeParticle: 0},
	{MainArray: 0},
	{SwapArray: 0},
	{Function: 0},
	{nosecandy: 0},
	{Texthi: 0},
	{nosecandy2: 0},
	{pos_abajo: 0},
	{pos_arriba: 0},
	{pos_derecha: 0},
	{pos_Izquierda: 0},
	{selector: 0},
	{txt_puntos: 0},
	{A_PANTALLA: 0},
	{TXT_LINEAS: 0},
	{TXT_NIVEL: 0},
	{TXT_PUNTOS2: 0},
	{ArrayRanking: 0},
	{btnUpdate: 0},
	{btnDelete: 0},
	{Textuid: 0},
	{Texto: 0},
	{marcos_de_icono: 0},
	{degrade: 0},
	{marcos_de_icono2: 0},
	{canti_pesos: 0},
	{icono_dinero: 0},
	{ico_retirar_dinero: 0},
	{Sprite: 0},
	{canti_puntos: 0},
	{PUBLICIDA: 0},
	{ICO_PREMIADOS: 0},
	{ICO_INTER_PREMIADO: 0},
	{ICO_COFRES: 0},
	{canti_creditos: 0},
	{ir_juegos_cofres: 0},
	{CANTIDA_TEXTO: 0},
	{box_Alias: 0},
	{tex_correo: 0},
	{nick_name: 0},
	{boton_login: 0},
	{CANT_TIEMPO_VIDEO: 0},
	{CANT_CREDITOS: 0},
	{atras: 0},
	{Fecha: 0},
	{marcos_de_icono3: 0},
	{tex_slot_machine: 0},
	{texporslot1: 0},
	{texporslot2: 0},
	{texporslot3: 0},
	{boton_slot: 0},
	{FondoEnMosaico: 0},
	{Girar: 0},
	{ruleta: 0},
	{flecha_ruleta: 0},
	{monedas: 0},
	{Pegado: 0},
	{palitos: 0},
	{MoverA: 0},
	{tex_winner_ruleta: 0},
	{BTON_atras: 0},
	{msj: 0},
	{ico_ruleta: 0},
	{Persistencia: 0},
	{ChatLog: 0},
	{PeerList: 0},
	{ChatTextBox: 0},
	{SendButton: 0},
	{CHAT: 0},
	{Sprite6: 0},
	{tex_winner_ruleta2: 0},
	{cupon_regalo: 0},
	{boton_BORRAR: 0},
	{Tex_tex: 0},
	{Sprite9: 0},
	{aceptar_tex: 0},
	{Sprite13: 0},
	{marcos_de_icono4: 0},
	{clickruleta: 0},
	{clickslotmachin: 0},
	{Sprite14: 0},
	{"9patch": 0},
	{Rope: 0},
	{Valuable: 0},
	{TextFont: 0},
	{Sprite15: 0},
	{ir_miner: 0},
	{Sprite16: 0},
	{controltactil: 0},
	{"8Direcciones": 0},
	{playercop: 0},
	{Seno: 0},
	{Sprite18: 0},
	{solidoizquierdo: 0},
	{Scored: 0},
	{solidoderecha: 0},
	{Plataforma: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{solido2: 0},
	{PUNTOS: 0},
	{SWINGCOPTER_ICO: 0},
	{Sprite17: 0},
	{BTON_atras2: 0},
	{Sprite22: 0},
	{BTON_atras3: 0},
	{ico_app: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{box_nombres: 0},
	{box_Password: 0},
	{tex_recuperar_password: 0},
	{tex_crear_cuenta: 0},
	{Botón_entrar: 0},
	{Botón_registrar: 0},
	{box_user: 0},
	{tex_info: 0},
	{TEXTO_LOGEO_GLOBAL: 0},
	{text_nombres: 0},
	{naranja_ico: 0},
	{texporslot4: 0},
	{texporslot5: 0},
	{marcos_de_confirmacion: 0},
	{Tex_confir: 0},
	{retirar_pesos: 0},
	{retirar_dolares: 0},
	{ICO_PREMIADOS2: 0},
	{ICO_PREMIADOS3: 0},
	{ICO_PREMIADOS4: 0},
	{CANT_TIEMPO_VIDEO2: 0},
	{CANT_TIEMPO_VIDEO3: 0},
	{CANT_TIEMPO_VIDEO4: 0},
	{Sprite26: 0},
	{canti_dolares: 0},
	{marcos_de_confirmacion2: 0},
	{Tex_confir2: 0},
	{Tex_dolar: 0},
	{Tex_pesos: 0},
	{configuracion: 0},
	{cambiar_pesos_a_puntos: 0},
	{cambiar_dolar_a_puntos: 0},
	{Text_tutorial: 0},
	{Sprite28: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{AYUDA: 0},
	{Sprite11: 0},
	{candybackgroundmeni: 0},
	{menuplaybtn: 0},
	{musiconoff: 0},
	{fondo_gandy: 0},
	{machtbackground: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles6: 0},
	{EsPareja: 0},
	{IsMoving: 0},
	{Trigger: 0},
	{Color: 0},
	{Col: 0},
	{DY: 0},
	{BlockY: 0},
	{Row: 0},
	{Peram: 0},
	{elegida: 0},
	{Block: 0},
	{PopUp: 0},
	{Arr_X: 0},
	{Arr_Y: 0},
	{Col2: 0},
	{Particles: 0},
	{Rotate: 0},
	{Replybtn: 0},
	{active: 0},
	{LoadingBar: 0},
	{black: 0},
	{pausa_candy: 0},
	{gamesover_camdy: 0},
	{Textyours: 0},
	{bara_score_candy: 0},
	{bton_time_creditos: 0},
	{home_candy: 0},
	{bton_time_publi: 0},
	{yourscoretxt: 0},
	{cant_creditos_candy: 0},
	{cant_time_candy: 0},
	{Textyourshiscore2: 0},
	{colisionar: 0},
	{creadores: 0},
	{Sprite12: 0},
	{Textyours2: 0},
	{logo: 0},
	{doble_puntos: 0},
	{tex_doble_puntos: 0},
	{logovicios: 0},
	{Desvanecer: 0},
	{cortina_despejar: 0},
	{Sprite27: 0},
	{Texto2: 0},
	{testercol1: 0},
	{arraysdas: 0},
	{publicidadbaner: 0},
	{Sólido: 0},
	{muros: 0},
	{fondo: 0},
	{muros_mono: 0},
	{DIALOGO_LOGO: 0},
	{texto_credto: 0},
	{PARTICULASCOINS: 0},
	{Sprite29: 0},
	{fondotetris: 0},
	{ladrillos: 0},
	{FondoEnMosaico2: 0},
	{xlineas: 0},
	{ylineas: 0},
	{ESTADO: 0},
	{BORDE: 0},
	{Parpadeo: 0},
	{lineas_block: 0},
	{ACTIVO: 0},
	{ORIGINAL: 0},
	{FIGURA: 0},
	{duplicado: 0},
	{CAIDA: 0},
	{blockes: 0},
	{Partículas: 0},
	{boton_izquierda_tetris: 0},
	{boton_derecha_tetris: 0},
	{boton_rotar_tetris: 0},
	{boton_bajar_tetris: 0},
	{finpartida_tetris: 0},
	{tetris_menu_screen: 0},
	{cuadro_gameover: 0},
	{fondo_pantalla_tetris_menu: 0},
	{BOTON_PLAY_TETRIS: 0},
	{Sprite31: 0},
	{iconoboton_play: 0},
	{btnSave: 0},
	{btncancel: 0},
	{inputScore: 0},
	{inputName: 0},
	{txtRanking: 0},
	{FondoEnMosaico3: 0},
	{Sprite7: 0},
	{Sprite30: 0},
	{Sprite32: 0},
	{Partículas2: 0},
	{Físicas: 0},
	{piso: 0},
	{bton_creditos_cofre: 0},
	{bton_creditos_cofre_dinero: 0},
	{Sprite33: 0},
	{pantall_carga: 0},
	{Sprite34: 0},
	{Sprite10: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{ACEPTAR_TUTORIAL_ICO: 0},
	{aceptar_TUTORIAL: 0},
	{Text_tutorial2: 0},
	{bton_cargar: 0},
	{Tex_cargar_datos: 0},
	{bton_guardar: 0},
	{BOTON_PLAY_TETRIS2: 0},
	{Tex_guardarcargar: 0},
	{tex_fps: 0},
	{casilla: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Texto3: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Lighten: 0},
	{direcion: 0},
	{Alias: 0},
	{DOLARES: 0},
	{PESOS: 0},
	{CREDITOS: 0},
	{TIEMPO_VIDEO: 0},
	{TIEMPO_VIDEO1: 0},
	{TIEMPO_VIDEO2: 0},
	{TIEMPO_VIDEO3: 0},
	{TIEMPO_INTER_RECOMPENSA: 0},
	{TOQUES_INTER: 0},
	{conectado: 0},
	{GUIA: 0},
	{versionapp: 0},
	{nombres: 0},
	{argento: 0},
	{abc1: 0},
	{aaa: 0},
	{aaa2: 0},
	{aaa3: 0},
	{aaa4: 0},
	{aaa5: 0},
	{can11: 0},
	{abc2: 0},
	{TouchPanID: 0},
	{TouchLastX: 0},
	{TouchLastY: 0},
	{boto_ayuda: 0},
	{guardar_cargar_datos: 0},
	{SecondsPerObstacle: 0},
	{JumpStrength: 0},
	{SCROLLSPEED: 0},
	{Score: 0},
	{gamestart: 0},
	{FirstInteraction: 0},
	{DOUBLESPAWNRATE: 0},
	{BOMBSPAWNRATE: 0},
	{SCREENHORIZONTALMARGIN: 0},
	{RotationDirection: 0},
	{AllowPlayerToCut: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{RandomForce: 0},
	{Score2: 0},
	{GameIsOver: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0},
	{Pause: 0},
	{HighScore: 0},
	{GameOn: 0},
	{Score3: 0},
	{IsMatched: 0},
	{X: 0},
	{Y: 0},
	{On: 0},
	{IsTouched: 0},
	{Tile: 0},
	{doblepuntostime: 0},
	{timpo_recom_candy: 0},
	{PASAR_NIVEL: 0},
	{NIVEL: 0},
	{LINEAS: 0},
	{PUNTOS2: 0},
	{ESPACIO: 0},
	{caida: 0},
	{velocidad_blockes: 0},
	{musica_tetris: 0},
	{userID: 0},
	{numerOfPlayers: 0},
	{playerInformation: 0},
	{ranking: 0},
	{url: 0},
	{borderRadius: 0},
	{suerte: 0},
	{tiempo_video_suerte_cofre: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	AlmacenamientoLocal: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AnuncioEnMóvil: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	ENVIAR: class extends self.ISpriteInstance {},
	RECIVIR: class extends self.ISpriteInstance {},
	slot1: class extends self.ISpriteInstance {},
	slot2: class extends self.ISpriteInstance {},
	slot3: class extends self.ISpriteInstance {},
	icono: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	AirDust: class extends self.IParticlesInstance {},
	AvailablePositions: class extends self.IArrayInstance {},
	GameData: class extends self.IArrayInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Level: class extends self.ISpriteInstance {},
	Sparks: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ISpriteInstance {},
	Blade: class extends self.ISpriteInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	FireParticles: class extends self.IParticlesInstance {},
	GameManager2: class extends self.ISpriteInstance {},
	HalfObject: class extends self.ISpriteInstance {},
	InstructionsText: class extends self.ITextInstance {},
	JuiceParticles: class extends self.IParticlesInstance {},
	Object: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	SliceText: class extends self.ITextInstance {},
	SmokeParticle: class extends self.IParticlesInstance {},
	MainArray: class extends self.IArrayInstance {},
	SwapArray: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	nosecandy: class extends self.ISpriteInstance {},
	Texthi: class extends self.ITextInstance {},
	nosecandy2: class extends self.ISpriteInstance {},
	pos_abajo: class extends self.ISpriteInstance {},
	pos_arriba: class extends self.ISpriteInstance {},
	pos_derecha: class extends self.ISpriteInstance {},
	pos_Izquierda: class extends self.ISpriteInstance {},
	selector: class extends self.ISpriteInstance {},
	txt_puntos: class extends self.ITextInstance {},
	A_PANTALLA: class extends self.IArrayInstance {},
	TXT_LINEAS: class extends self.ITextInstance {},
	TXT_NIVEL: class extends self.ITextInstance {},
	TXT_PUNTOS2: class extends self.ITextInstance {},
	ArrayRanking: class extends self.IArrayInstance {},
	btnUpdate: class extends self.IButtonInstance {},
	btnDelete: class extends self.IButtonInstance {},
	Textuid: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	marcos_de_icono: class extends self.ISpriteInstance {},
	degrade: class extends self.ISpriteInstance {},
	marcos_de_icono2: class extends self.ISpriteInstance {},
	canti_pesos: class extends self.ITextInstance {},
	icono_dinero: class extends self.ISpriteInstance {},
	ico_retirar_dinero: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	canti_puntos: class extends self.ITextInstance {},
	ICO_PREMIADOS: class extends self.ISpriteInstance {},
	ICO_INTER_PREMIADO: class extends self.ISpriteInstance {},
	ICO_COFRES: class extends self.ISpriteInstance {},
	canti_creditos: class extends self.ITextInstance {},
	ir_juegos_cofres: class extends self.ISpriteInstance {},
	box_Alias: class extends self.ITextInputInstance {},
	tex_correo: class extends self.ITextInstance {},
	nick_name: class extends self.ITextInstance {},
	boton_login: class extends self.ISpriteInstance {},
	CANT_TIEMPO_VIDEO: class extends self.ITextInstance {},
	CANT_CREDITOS: class extends self.ITextInstance {},
	atras: class extends self.ISpriteInstance {},
	Fecha: class extends self.IInstance {},
	marcos_de_icono3: class extends self.ISpriteInstance {},
	tex_slot_machine: class extends self.ITextInstance {},
	texporslot1: class extends self.ISpriteInstance {},
	texporslot2: class extends self.ISpriteInstance {},
	texporslot3: class extends self.ISpriteInstance {},
	boton_slot: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	ruleta: class extends self.ISpriteInstance {},
	flecha_ruleta: class extends self.ISpriteInstance {},
	palitos: class extends self.ISpriteInstance {},
	tex_winner_ruleta: class extends self.ITextInstance {},
	BTON_atras: class extends self.ISpriteInstance {},
	msj: class extends self.ITextInputInstance {},
	ico_ruleta: class extends self.ISpriteInstance {},
	ChatLog: class extends self.ITextInputInstance {},
	PeerList: class extends self.IListInstance {},
	ChatTextBox: class extends self.ITextInputInstance {},
	SendButton: class extends self.IButtonInstance {},
	CHAT: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	tex_winner_ruleta2: class extends self.ITextInstance {},
	cupon_regalo: class extends self.ITextInstance {},
	boton_BORRAR: class extends self.ISpriteInstance {},
	Tex_tex: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	aceptar_tex: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	marcos_de_icono4: class extends self.ISpriteInstance {},
	clickruleta: class extends self.ITextInstance {},
	clickslotmachin: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	Rope: class extends self.ITiledBackgroundInstance {},
	Valuable: class extends self.ISpriteInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	ir_miner: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	playercop: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	solidoizquierdo: class extends self.ISpriteInstance {},
	solidoderecha: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	solido2: class extends self.ISpriteInstance {},
	PUNTOS: class extends self.ISpriteInstance {},
	SWINGCOPTER_ICO: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	BTON_atras2: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	BTON_atras3: class extends self.ISpriteInstance {},
	ico_app: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	box_nombres: class extends self.ITextInputInstance {},
	box_Password: class extends self.ITextInputInstance {},
	tex_recuperar_password: class extends self.ITextInstance {},
	tex_crear_cuenta: class extends self.ITextInstance {},
	Botón_entrar: class extends self.IButtonInstance {},
	Botón_registrar: class extends self.IButtonInstance {},
	box_user: class extends self.ITextInputInstance {},
	tex_info: class extends self.ITextInstance {},
	TEXTO_LOGEO_GLOBAL: class extends self.ITextInstance {},
	text_nombres: class extends self.ITextInstance {},
	naranja_ico: class extends self.ISpriteInstance {},
	texporslot4: class extends self.ISpriteInstance {},
	texporslot5: class extends self.ISpriteInstance {},
	marcos_de_confirmacion: class extends self.ISpriteInstance {},
	Tex_confir: class extends self.ITextInstance {},
	retirar_pesos: class extends self.ITextInstance {},
	retirar_dolares: class extends self.ITextInstance {},
	ICO_PREMIADOS2: class extends self.ISpriteInstance {},
	ICO_PREMIADOS3: class extends self.ISpriteInstance {},
	ICO_PREMIADOS4: class extends self.ISpriteInstance {},
	CANT_TIEMPO_VIDEO2: class extends self.ITextInstance {},
	CANT_TIEMPO_VIDEO3: class extends self.ITextInstance {},
	CANT_TIEMPO_VIDEO4: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	canti_dolares: class extends self.ITextInstance {},
	marcos_de_confirmacion2: class extends self.ISpriteInstance {},
	Tex_confir2: class extends self.ITextInstance {},
	Tex_dolar: class extends self.ITextInstance {},
	Tex_pesos: class extends self.ITextInstance {},
	configuracion: class extends self.ISpriteInstance {},
	cambiar_pesos_a_puntos: class extends self.ISpriteInstance {},
	cambiar_dolar_a_puntos: class extends self.ISpriteInstance {},
	Text_tutorial: class extends self.ITextInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	AYUDA: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	candybackgroundmeni: class extends self.ISpriteInstance {},
	menuplaybtn: class extends self.ISpriteInstance {},
	musiconoff: class extends self.ISpriteInstance {},
	fondo_gandy: class extends self.ISpriteInstance {},
	machtbackground: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Block: class extends self.ISpriteInstance {},
	PopUp: class extends self.ISpriteInstance {},
	Col2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Replybtn: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	pausa_candy: class extends self.ISpriteInstance {},
	gamesover_camdy: class extends self.ITextInstance {},
	Textyours: class extends self.ITextInstance {},
	bara_score_candy: class extends self.ISpriteInstance {},
	bton_time_creditos: class extends self.ISpriteInstance {},
	home_candy: class extends self.ISpriteInstance {},
	bton_time_publi: class extends self.ISpriteInstance {},
	yourscoretxt: class extends self.ITextInstance {},
	cant_creditos_candy: class extends self.ITextInstance {},
	cant_time_candy: class extends self.ITextInstance {},
	Textyourshiscore2: class extends self.ITextInstance {},
	creadores: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Textyours2: class extends self.ITextInstance {},
	logo: class extends self.ISpriteInstance {},
	doble_puntos: class extends self.ISpriteInstance {},
	tex_doble_puntos: class extends self.ITextInstance {},
	logovicios: class extends self.ISpriteInstance {},
	cortina_despejar: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	testercol1: class extends self.ISpriteInstance {},
	arraysdas: class extends self.ITextInstance {},
	publicidadbaner: class extends self.ISpriteInstance {},
	muros: class extends self.ISpriteInstance {},
	fondo: class extends self.ITiledBackgroundInstance {},
	muros_mono: class extends self.ISpriteInstance {},
	DIALOGO_LOGO: class extends self.ISpriteInstance {},
	texto_credto: class extends self.ITextInstance {},
	PARTICULASCOINS: class extends self.IParticlesInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	fondotetris: class extends self.ISpriteInstance {},
	ladrillos: class extends self.ISpriteInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	lineas_block: class extends self.ISpriteInstance {},
	blockes: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	boton_izquierda_tetris: class extends self.ISpriteInstance {},
	boton_derecha_tetris: class extends self.ISpriteInstance {},
	boton_rotar_tetris: class extends self.ISpriteInstance {},
	boton_bajar_tetris: class extends self.ISpriteInstance {},
	finpartida_tetris: class extends self.ISpriteInstance {},
	tetris_menu_screen: class extends self.ISpriteInstance {},
	cuadro_gameover: class extends self.ISpriteInstance {},
	fondo_pantalla_tetris_menu: class extends self.ISpriteInstance {},
	BOTON_PLAY_TETRIS: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	iconoboton_play: class extends self.ISpriteInstance {},
	btnSave: class extends self.IButtonInstance {},
	btncancel: class extends self.IButtonInstance {},
	inputScore: class extends self.ITextInputInstance {},
	inputName: class extends self.ITextInputInstance {},
	txtRanking: class extends self.ITextInstance {},
	FondoEnMosaico3: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Partículas2: class extends self.IParticlesInstance {},
	piso: class extends self.ISpriteInstance {},
	bton_creditos_cofre: class extends self.ISpriteInstance {},
	bton_creditos_cofre_dinero: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	pantall_carga: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	ACEPTAR_TUTORIAL_ICO: class extends self.ISpriteInstance {},
	aceptar_TUTORIAL: class extends self.ITextInstance {},
	Text_tutorial2: class extends self.ITextInstance {},
	bton_cargar: class extends self.ISpriteInstance {},
	Tex_cargar_datos: class extends self.ITextInstance {},
	bton_guardar: class extends self.ISpriteInstance {},
	BOTON_PLAY_TETRIS2: class extends self.ISpriteInstance {},
	Tex_guardarcargar: class extends self.ITextInstance {},
	tex_fps: class extends self.ITextInstance {},
	casilla: class extends self.IButtonInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Lighten: class extends self.ISpriteInstance {},
	direcion: class extends self.ISpriteInstance {}
}